### ISSUE TITLE
Problemas con desplazamientos mayores a 1

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/cifrado-cesar#1]
Cuando se modifica el desplazamiento a valores mayores a uno, los caracteres codificados fallan aleatoriamente.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cifrado - Problemas desplazamientos](https://trello.com/c/C2HQNWe3/16-cifrado-problemas-desplazamientos)

**Comment by DanielScha** [comment]
Hago este!
