### ISSUE TITLE
Auto cifrado

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/cifrado-cesar#2]
Cuando se modifica el desplazamiento, el valor del string codificado se mantiene igual. Estaría bueno modificar el valor en tiempo real al momento del cambio de desplazamiento.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cifrado - Autocifrado](https://trello.com/c/Z9Qbtspj/17-cifrado-autocifrado)

**Comment by grotatori** [comment]
Tomo este!

**Comment by zeratulmdq** [comment]
Ojo que para este *creo* deberia estar resuelto el #1

**Comment by grotatori** [comment]
Me fijo si lo puedo resolver igual, a lo sumo el bug del #1 se seguira viendo
